idf_component_register(SRCS
                        "main.c"
                        "clock_discipline.c"
                        "clock_math.c"
                        "gps_receiver.c"
                        "ethernet_w5500.c"
                        "ntp_server.c"
                        "oled_display.c"
                    INCLUDE_DIRS ".")
